### PR TITLE
- Added "Set Version" Task

### PR DESCRIPTION
**Pull request by eNeRGy164**
- Silenced some PowerShell output when building VSIX

### CODE REVIEW

**Comment by WaelHamze** [comment]
Thx for contributing and creating another tasks which I am sure will be welcomed by the users. One question, what do you supply as an input to the version number in your builds? is it a fixed value or somehow you generate it at runtime?

**Comment by jordimontana82** [comment]
This is really good! 

What about versioning based of a TFS / Git tag? Normally the major numbers belong to releases and the minor ones to bug fixes / build number.

If the Version nº could be compose of a TFS tag + changeset it would be ideal I think as you could cover both scenarios where people might decide to increment the version number (i.e. being it released / feature based) and also let the CI script append also the changeset nº for all the changesets which have the same TFS tag.

What do you think Wael?

**Comment by eNeRGy164** [comment]
I use multiple scenario's. Normally I use an auto-increment scenario during a sprint and reset the major part on release. That's why I needed to set the version specifically from a variable I enter on the start of the release.
I will extend this function in the future so you can enter an auto-increment pattern like x.1.x.x or x.x.1.0 so you have even more control.

**Comment by WaelHamze** [comment]
Hi Jordi, Yes you could generate version number based on tags/changesets/commits etc...
I would put that logic however outside of this task, perhaps in another task and then pass the output of that as an input to this task. The version number generation could be used in other places too.

**Comment by jordimontana82** [comment]
Yep, agree 👍

**Pull request merged**
