### PR TITLE
fix for connection using oauth / OrganizationWebProxyClient

### LINKED ISSUE #198: OAuth -Connection to MSCRM to Ping Dynamics 365 from VSTS Agent failing
Dear Wael @WaelHamze 

Please help , I am using Dynamics 365 Sandbox and trying to connect using OAuth for a user ABC in our company ABCDomain with AppId in Azure but failing. The same connection works with .NET code (using Microsoft.Xrm.Tooling.Connector;) from local machine 

[section]Starting: Inline Powershell
============
Task         : Run Inline Powershell
Description  : Run the Powershell from a textbox
Version      : 1.1.7
Author       : Peter Groenewegen - Xpirit
Hello world AuthType=OAuth;Url=https://OrgName.crm4.dynamics.com;Username=ABC@ABCDomain.onmicrosoft.com;Password=***;AppId=gfdd252f-97d9-477d-a4c3-01480a672c6d;RedirectUri=http://localhost/;LoginPrompt=Auto;
[section]Finishing: Inline Powershell

[section]Starting: MSCRM CRM Ping OAuth
============
Task         : MSCRM Ping
Description  : A sample task that checks connectivity to a Dynamics 365 environment
Version      : 10.0.5
Author       : Wael Hamze
Help         : Performs a WhoAmIRequest against the target CRM environment
======
[error]Organization cannot be null or empty.
Parameter name: Organization Name
[section]Finishing: MSCRM CRM Ping OAuth

O365 connection went well
---------------------------------
It works with O365 (connection) connectivity with Hosted Agent and Private Agent
AuthType=Office365;Url=https://CRM334ada55.crm4.dynamics.com;Username=admin@CRM334ada55.onmicrosoft.com;Password=sss@Cggg34ada55

### PR DESCRIPTION
**Pull request by majakubowski**
resolves #198

### CODE REVIEW

**Comment by majakubowski** [comment]
resolves #198

**Comment by WaelHamze** [comment]
@majakubowski thanks for this, how do we set the timeout using the webclient?

The connection string doesn't support timeout, this useful for long running sync operations: https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/xrm-tooling/use-connection-strings-xrm-tooling-connect

**Comment by majakubowski** [comment]
@WaelHamze I found a magic static setting on CrmServiceClient. If set before creating client - it support both OrganizationServiceProxy / OrganizationWebProxyClient.

**Comment by WaelHamze** [comment]
@majakubowski this is awesome, I just about to make the same changes so you saved me sometime 👍

**Pull request merged**
