### PR TITLE
Created Update Secure Configuration Task

### PR DESCRIPTION
**Pull request by devkeydet**
I don't exactly know how to test this, but I took a stab at creating the task I offered to build.

https://github.com/WaelHamze/xrm-ci-framework/issues/42

Since this is my first attempt, I'm all ears for what I've missed and how I can do this better.  Thanks for considering my contribution.

### CODE REVIEW

**Comment by devkeydet** [comment]
So I just noticed that the pull request changes the sln file to target VS 2017.  Sorry about that.  Other than that, I tried to make sure there weren't any other side effects.  If the other parts look good, then I can fix the sln file.  Otherwise, I will fix it when I make any changes base on your feedback.

**Comment by WaelHamze** [comment]
Thanks a lot for creating the pull request.

Testing is not very difficult actually. I can show you the few steps.
1- Rebuild the solution
2- Make you updated this to include the task PackageFramework.ps1. Run this script it will copy all the task to the bin directory
3- Yo will need a VSTS instance that you can test this on. I suggest you use a different account than the one where the extension is installed
4- Install the TFX command line tools.
5- tfx login --service-url https://[account].visualstudio.com/defaultcollection --auth-type 'pat' --token '[token]'
(You can get a token from your user profile in VSTS)
6- upload the task from the bin directory
7- tfx build tasks upload --task-path .\MSCRMBackupOnlineInstance

Alternatively I will merge the pull request when I get a chance and release a new version that you can try.

**Comment by devkeydet** [comment]
Thanks!  I'll give this a shot.  Any suggestions on how to handle the fact that I'm using VS2017 and it changes the sln file?

**Comment by devkeydet** [comment]
The testing instructions were very helpful.  I found some issues with my code, fixed those issues, and tested everything is working as expected.  The latest commit should reflect a working task.  Please let me know your feedback.

**Comment by WaelHamze** [comment]
Thanks. Will package it soon once I finish the task. Will let you know once it is live.

**Pull request merged**
