### PR TITLE
four new cmdlets Remove-XrmWorkflow, Set-XrmWorkflowState, Remove-XrmOption, Set-XrmDashboardRole & other improvements 

### PR DESCRIPTION
**Pull request by majakubowski**
four new cmdlets:
- Remove-XrmWorkflow - remove workflow with dependencies;
  - workflow, which references workflow targeted do remove will be also removed,
  - BPF's, which use references workflow targeted to remove will be updated - workflow reference will be removed from BPF,
- Set-XrmWorkflowState - can be used to publish/unpublish workflow by name or pattern; during publishing cmdlet will try to fix broken record references,
- Remove-XrmOption - removes option from local or global optionset, useful to OOB optionsets,
- Set-XrmDashboardRole - allows set/unset security roles on dashboard specified by id or name, useful for OOB dashbaords,

other improvements:
 - SolutionManager in async mode should check also AsyncOperation statuscode to determine import result,
- deleting plugin/workflows with dependencies should track items to delete (from parent call) to block endless recurrence,
- skiping deleting hidden sdk message steps (handlers of synch. workflows),
- changes in removing workflows used in BPF's (like in Remove-XrmWorkflow),

### CODE REVIEW

**Comment by WaelHamze** [comment]
@majakubowski thanks for this PR, this is very useful, are you able to re-submit it based on the current code to avoid merging and conflicts?

**Comment by majakubowski** [comment]
@WaelHamze PR is updated :)

**Comment by WaelHamze** [comment]
@majakubowski is the reference to visual basic a must? I presume that is something that will be loaded as part of .NET framework on the host.

**Comment by majakubowski** [comment]
@WaelHamze it's part of the .NET framework. This is required becouse I'm using [TextFieldParser](
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.textfieldparser) - basic csv-like string parser used in XamlValuesHelper class to extract parameters from workflow's code. It can be probably replaced by some loops with regular expressions but I think this code is cleaner.

**Pull request merged**
