### PR TITLE
Retry to connect if CrmServiceClient is not ready

### PR DESCRIPTION
**Pull request by Bakanych**
Tried to solve #58
Not so elegant but it worked in our releases. Now I can successfully deploy big solution sets.
Also now users can see actual connection error message instead of Object reference not set to an instance of an object.

### CODE REVIEW

**Comment by Bakanych** [comment]
Also fixed issues with nuget packages and post-build action.

**Comment by WaelHamze** [comment]
@Bakanych thanks for this pull request. Quick questions. The connection is created in the BeginProcessing before the actual import solution logic is processed. I can understand a retry on opening a connection can sometimes help if there are network issues etc... Not sure I understand the correlation between the solution size and opening the connection?

**Comment by Bakanych** [comment]
>  Not sure I understand the correlation between the solution size and opening the connection

It's not about solution size.  We face this connection issue randomly for various solutions in every release. This retry really helps keep a task alive.
Not sure about the real issue cause, it might be our network issue or our 365 sandbox instance just works not so well.

**Comment by billpieper** [comment]
I haven't tried this code change -- but plan to in my environment.  I have been seeing similar issues randomly connecting to CRM instances.

**Pull request merged**
