### PR TITLE
add setpublishtheme command

### PR DESCRIPTION
**Pull request by MattTrinder1**
Adding a Cmdlet to allow users to publish a theme.

### CODE REVIEW

**Comment by WaelHamze** [comment]
@MattTrinder1 thanks for this. Very useful. How do you create/update the theme by the way?

Also do you think it would be more useful to provide the name instead of Guid (or as another option)?

**Comment by MattTrinder1** [comment]
@WaelHamze The theme is exported using Get-XrmEntities to retrieve the record, and then Export-CliXml to serialize it out to a file.  And then Import-CliXml, New-XrmEntity and Add-XrmEntity to import it (with some manual steps to only include the relevant theme fields.)

It would be easy enough to add an option to do publish by name rather than Id - I'll take a look.

It would probably also make sense to add CmdLets to Export and Import the theme records (so basically a wrapper around the steps above) again, I'll have a play.

**Comment by MattTrinder1** [comment]
ok - added an option to publish theme by name as well.  How do I test this ?  I can build the CmdLet assembly fine but can't get powershell to recognise my new built version - it just seems to always use the version installed by install-module ?

**Comment by WaelHamze** [comment]
@MattTrinder1 thanks for the changes. You could also use the configuration migration tool to move the themes around.

**Comment by s-bauer** [comment]
@WaelHamze Why was this added to the "CRM365" folder and not to "MSDYNV9"? I seem to can't access the `Publish-XrmTheme` command with the newest version of `Xrm.Framework.CI.PowerShell.Cmdlets`. Is there any reason for this? Otherwise I'll submit another PR to add this!

**Pull request merged**
