### PR TITLE
Bring back crm2015 import / export compatibility 

### PR DESCRIPTION
**Pull request by matthew-yee**
Love your work.
Tested against 2015 (7.0) and used within my current projects

### CODE REVIEW

**Comment by matthew-yee** [comment]
I could be wrong, its my understanding that the 2015 work doesnt integrate cleanly to devops build pipelines (guess i could always call out to the ps wrappers).

in addition, there seem to be a few tickets in the past around this not working and the solution being "its incompatible with the sdk". Guess this is my way of highlighting its not a sdk issue but more a "how you use it" issue.

Finally, i suspect that thers some really cool features in the ci framework which would not be ported to 2015 (2015 being long dead in many ways etc), that many would like to leverage, this give them and myself optiosn to ue the new tools / wrappers with minimal code change.

if the answer is you no longer support the 2015, i'm happy with that (super old and technically, i wouldn't want to be supporting it either), however, if there is a desire to have it work "best efforts", then heres the code

Ticket this rates to:
https://github.com/WaelHamze/xrm-ci-framework/issues/274

There are a few others which mention the "Unrecognized request parameter: ExportExternalApplications".

**Comment by MichaelHolmesWP** [comment]
Hi @matthew-yee, 

You make a valid point, I don't see the need for 2013/2015/2016 on prem support disappearing any time soon (I've had several larger enterprise clients still running older versions too, who can't upgrade due to budgeting / logistics/customisation issues without significant overhaul.)

I envision that given the release of a Microsoft-backed solution (Power Platform Build Tools) they will eventually reach feature parity with this project, at which point the primary advantage of this open source system will be the enhanced flexibility of the underlying xrmCiFramework and backwards compatibility (I highly doubt microsoft will ever build legacy support into their ADO tasks).

With this in mind it will be a big overhaul of the repo to get the 8.2/7.0/6.0 forks of the solution up to par with respect to unit tests etc. in order to get them into a state where people could independently maintain a particular version and have the one global dev ops task project correctly scoop up the versions and allow version selection, but I'll give it a shot. This way we can maintain stable, workable version copies and back-port new features from the V9 (& beyond) main branch as needed.

**Comment by matthew-yee** [comment]
@MichaelHolmesWP Thanks for the update and consideration, much appreciate it. I think it will add long term value for those stuck with older systems, especially with all the other very useful bits being integrated with the ci framework.

Matt

**Comment by WaelHamze** [comment]
@matthew-yee I think you missed a few functions :) But I get what you are trying to do. I'll fix the rest. I always wondered if there was any easy way to make this work. If these small changes will make these tasks/scripts usable by more projects then this would be a very quick win. I am looking forward to hear your feedback once this gets released.

**Pull request merged**
